version: "2"

services:
  web:
    image: nginx:1.13-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - "./docs:/usr/share/nginx/html:ro"

  node:
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - NPM_CONFIG_PREFIX=/home/node/.npm-global
      - PATH=$PATH:/home/node/.npm-global/bin
    ports:
      - 5000:5000
